/*
 * Copyright 2021-2022 Western Digital Corporation or its affiliates
 * Copyright 2022 Antmicro
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

// // pynq
#define VTA_COHERENT_ACCESSES false
#define VTA_COMPUTE_ADDR 0xB0002000
#define VTA_COMPUTE_BIAS_ADDR_OFFSET 40
#define VTA_COMPUTE_DONE_RD_OFFSET 24
#define VTA_COMPUTE_DONE_WR_OFFSET 16
#define VTA_COMPUTE_UOP_ADDR_OFFSET 32
#define VTA_FETCH_ADDR 0xB0000000
#define VTA_FETCH_INSN_ADDR_OFFSET 24
#define VTA_FETCH_INSN_COUNT_OFFSET 16
#define VTA_HW_VER 0.0.2
#define VTA_IP_REG_MAP_RANGE 0x1000
#define VTA_LOAD_ADDR 0xB0001000
#define VTA_LOAD_INP_ADDR_OFFSET 16
#define VTA_LOAD_WGT_ADDR_OFFSET 24
#define VTA_LOG_ACC_BUFF_SIZE 17
#define VTA_LOG_ACC_WIDTH 5
#define VTA_LOG_BATCH 0
#define VTA_LOG_BLOCK 4
#define VTA_LOG_BLOCK_IN 4
#define VTA_LOG_BLOCK_OUT 4
#define VTA_LOG_BUS_WIDTH 6
#define VTA_LOG_INP_BUFF_SIZE 15
#define VTA_LOG_INP_WIDTH 3
#define VTA_LOG_OUT_BUFF_SIZE 15
#define VTA_LOG_OUT_WIDTH 3
#define VTA_LOG_UOP_BUFF_SIZE 15
#define VTA_LOG_WGT_BUFF_SIZE 18
#define VTA_LOG_WGT_WIDTH 3
#define VTA_STORE_ADDR 0xB0003000
#define VTA_STORE_OUT_ADDR_OFFSET 16

// sim
// #define VTA_COHERENT_ACCESSES true
// #define VTA_COMPUTE_ADDR 0x43C02000
// #define VTA_COMPUTE_BIAS_ADDR_OFFSET 40
// #define VTA_COMPUTE_DONE_RD_OFFSET 24
// #define VTA_COMPUTE_DONE_WR_OFFSET 16
// #define VTA_COMPUTE_UOP_ADDR_OFFSET 32
// #define VTA_FETCH_ADDR 0x43C00000
// #define VTA_FETCH_INSN_ADDR_OFFSET 24
// #define VTA_FETCH_INSN_COUNT_OFFSET 16
// #define VTA_HW_VER 0.0.2
// #define VTA_IP_REG_MAP_RANGE 0x1000
// #define VTA_LOAD_ADDR 0x43C01000
// #define VTA_LOAD_INP_ADDR_OFFSET 16
// #define VTA_LOAD_WGT_ADDR_OFFSET 24
// #define VTA_LOG_ACC_BUFF_SIZE 17
// #define VTA_LOG_ACC_WIDTH 5
// #define VTA_LOG_BATCH 0
// #define VTA_LOG_BLOCK 4
// #define VTA_LOG_BLOCK_IN 4
// #define VTA_LOG_BLOCK_OUT 4
// #define VTA_LOG_BUS_WIDTH 6
// #define VTA_LOG_INP_BUFF_SIZE 15
// #define VTA_LOG_INP_WIDTH 3
// #define VTA_LOG_OUT_BUFF_SIZE 15
// #define VTA_LOG_OUT_WIDTH 3
// #define VTA_LOG_UOP_BUFF_SIZE 15
// #define VTA_LOG_WGT_BUFF_SIZE 18
// #define VTA_LOG_WGT_WIDTH 3
// #define VTA_STORE_ADDR 0x43C03000
// #define VTA_STORE_OUT_ADDR_OFFSET 16
